name: Continuous integration
on:
  pull_request: # All
  push:
    branches:
    - main
jobs:
  hygiene-tests:
    name: Repository hygiene
    runs-on: ubuntu-latest
    steps:
    - name: Job information
      run: |
        echo "Job information"
        echo "Trigger: ${{ github.event_name }}"
        echo "Host: ${{ runner.os }}"
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref }}"
        docker images
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Python lint
      run: make python-lint
    - name: Automated hygiene verification
      run: make check-hygiene
    - name: uss_qualifier documentation validation
      run: make validate-uss-qualifier-docs
    - name: Shell lint
      run: make shell-lint

  monitorlib-test:
    name: monitorlib tests
    uses: ./.github/workflows/monitoring-test.yml
    with:
      name: monitorlib
      script: |
        cd monitoring/monitorlib
        make test

  mock_uss-test:
    name: mock_uss tests
    uses: ./.github/workflows/monitoring-test.yml
    with:
      name: mock_uss
      script: |
        cd monitoring/mock_uss
        make test

  uss_qualifier-test:
    name: uss_qualifier tests
    uses: ./.github/workflows/monitoring-test.yml
    with:
      name: uss_qualifier
      script: |
        sudo apt install linux-modules-extra-$(uname -r)
        sudo cat /proc/sys/net/netfilter/nf_conntrack_max
        sudo cat /proc/sys/net/core/somaxconn
        sudo cat /proc/sys/net/ipv4/tcp_max_syn_backlog
        sudo sysctl net.ipv4.ip_local_port_range
        sudo sysctl net.ipv4.tcp_fin_timeout
        sudo sysctl net.ipv4.tcp_max_syn_backlog=16384
        sudo cat /proc/sys/net/ipv4/tcp_max_syn_backlog
        sudo sysctl -w net.ipv4.neigh.default.gc_thresh3=4096
        sudo sysctl fs.inotify.max_user_instances=1048576
        sudo prlimit --pid $$ --nofile=1048576:1048576
        sudo sysctl fs.inotify.max_user_instances=1280
        sudo sysctl fs.inotify.max_user_watches=655360
        sudo sysctl net.core.netdev_max_backlog=65536
        sudo tcpdump -nn -i any -w /tmp/sntp.cap &
        sudo sh -c 'while true; do ss -s ; ss -ti ; sysctl fs.file-nr ; netstat -s ; date ; sleep 10; done' &
        sudo sh -c 'while true; do lsof -n | wc -l ; date ; sleep 30; done' &
        sleep 1

        export CONFIG_NAME="" \
          USS_QUALIFIER_STOP_FAST=true

        cd monitoring/uss_qualifier
        make test

  uss_qualifier_F3411-19-test:
    name: uss_qualifier F3411-19 tests
    uses: ./.github/workflows/monitoring-test.yml
    with:
      name: uss_qualifier_F3411-19
      script: |
        export CONFIG_NAME=configurations.dev.netrid_v19 \
          USS_QUALIFIER_STOP_FAST=true

        cd monitoring/uss_qualifier
        make test

  prober-test:
    name: prober tests
    uses: ./.github/workflows/monitoring-test.yml
    with:
      name: prober
      script: |
        cd monitoring/prober
        make test
