name: 'Run a monitoring test (re-usable workflow)'

on:
  workflow_call:
    inputs:
      name:
        description: 'Name of the monitoring test.'
        required: true
        type: string
      script:
        description: 'Bash script running the monitoring test.'
        required: true
        type: string

jobs:
  monitoring-test:
#    runs-on: ubuntu-20.04
    runs-on: ubuntu-latest
    name: ${{ inputs.name }} test
    steps:
    - name: Job information
      run: |
        echo "Job information"
        echo "Trigger: ${{ github.event_name }}"
        echo "Host: ${{ runner.os }}"
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref }}"
        docker images
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Run ${{ inputs.name }} test
      run: ${{ inputs.script }}
    - name: Save containers and tracer logs as artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: monitoring-test-${{ inputs.name }}-logs
        path: |
          logs
          monitoring/mock_uss/output
    - name: Save USS qualifier reports as artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: monitoring-test-${{ inputs.name }}-reports
        path: |
          monitoring/uss_qualifier/output
          monitoring/prober/output
    # todo: remove me
    - name: Prepare capture
      if: always()
      run: |
        if [ -f /tmp/sntp.cap ]; then
          sleep 1
          sudo kill -2 $(pgrep tcpdump)
          journalctl -xu docker.service > /tmp/dockerlogs
          sleep 1
        fi
    # todo: remove me
    - name: Upload capture
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: capture-${{ inputs.name }}
        path: |
          /tmp/sntp.cap
    # todo: docker logs
    - name: Upload capture
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: capture-${{ inputs.name }}-dockerlogs
        path: |
          /tmp/sntp.cap
          /tmp/dockerlogs
